-- SELECT asks for confirmation; B or SELECT resume, A or START leave, and an
-- abandoned classic game does not touch the statistics.
T.run(function()
  T.boot(T.LANG.FR)
  local before = T.save()
  T.menu_start(T.MENU.CLASSIC)
  T.type_word("TER")
  T.press(T.K.SELECT); T.wait(2)
  T.check_eq(T.screen(), T.SCREEN.GAME, "the question is asked inside the game screen")
  T.shot("confirm")
  T.press(T.K.A); T.wait(3)
  T.check_eq(T.screen(), T.SCREEN.MENU, "SELECT then A quits to the menu")

  T.menu_start(T.MENU.CLASSIC)
  T.type_word("TER")
  T.press(T.K.SELECT); T.wait(2); T.press(T.K.B); T.wait(2)
  T.check_eq(T.screen(), T.SCREEN.GAME, "SELECT then B stays in the game")
  T.check_eq(T.game().current, "TER", "typed letters are kept")
  T.press(T.K.SELECT); T.wait(2); T.press(T.K.SELECT); T.wait(2)
  T.check_eq(T.screen(), T.SCREEN.GAME, "SELECT twice cancels as well")
  T.goto_key("R"); T.press(T.K.A)
  T.check_eq(T.game().current, "TERR", "typing works after cancelling")

  T.press(T.K.SELECT); T.wait(2)
  local c = T.kb()
  T.press(T.K.LEFT); T.press(T.K.DOWN)
  T.check_eq(T.kb().row .. "," .. T.kb().col, c.row .. "," .. c.col, "the D-pad is ignored while asking")
  T.press(T.K.START); T.wait(3)
  T.check_eq(T.screen(), T.SCREEN.MENU, "START confirms the quit like A")

  local s = T.save()
  T.check_eq(s.played, before.played, "an abandoned classic game is not counted")
  T.check_eq(s.streak, before.streak, "streak untouched")
end)
