-- Sound option: effects reach the tone generators when on, nothing when
-- off, and the setting is remembered.
T.run(function()
  T.boot(T.LANG.FR)
  T.set_sound(1)
  T.snd_reset()
  T.press(T.K.DOWN)
  T.check(T.snd.sq1 > 0, "menu tick plays")
  T.menu_start(T.MENU.CLASSIC)
  T.snd_reset()
  T.type_word("TERRE")
  T.check(T.snd.sq1 > 0, "key clicks play")
  T.snd_reset()
  T.submit()
  T.check(T.snd.sq1 > 0 or T.snd.sq2 > 0, "reveal notes play")
  T.quit(true)

  T.set_sound(0)
  T.snd_reset()
  T.press(T.K.DOWN); T.press(T.K.UP)
  T.check_eq(T.snd.sq1, 0, "no menu tick when off")
  T.menu_start(T.MENU.CLASSIC)
  T.snd_reset()
  T.type_word("AAAAA"); T.press(T.K.START); T.wait(3)
  T.check_eq(T.snd.sq1 + T.snd.sq2 + T.snd.noise, 0, "no click, no buzzer when off")
  for _ = 1, 5 do T.press(T.K.B) end
  T.type_word("TERRE"); T.submit()
  T.check_eq(T.snd.sq1 + T.snd.sq2, 0, "no reveal notes when off")
  T.quit(true)
  T.check_eq(T.save().sound_on, 0, "setting persisted")

  T.set_sound(1)
  T.snd_reset()
  T.press(T.K.DOWN)
  T.check(T.snd.sq1 > 0, "sound is back")
  T.menu_go(T.MENU.CLASSIC)
end)
