-- Switching to English: QWERTY layout, English word list, and back.
T.run(function()
  T.boot(T.LANG.FR)
  T.set_language(T.LANG.EN)
  T.shot("menu_en")
  T.menu_start(T.MENU.CLASSIC)
  T.check_eq(T.game().lang, T.LANG.EN, "game in English")
  T.check_eq(T.kb().row .. "," .. T.kb().col, "0,0", "cursor on the first key")
  T.press(T.K.A)
  T.check_eq(T.game().current, "Q", "first key of the top row is Q (QWERTY)")
  T.press(T.K.B)
  T.type_word("TERRE"); T.press(T.K.START); T.wait(3)
  T.check_eq(T.game().n_guesses, 0, "a French word is not in the English list")
  for _ = 1, 5 do T.press(T.K.B) end
  T.type_word("CRANE"); T.submit()
  T.check_eq(T.game().n_guesses, 1, "an English word is accepted")
  T.shot("game_en")
  T.quit(true)

  T.set_language(T.LANG.FR)
  T.menu_start(T.MENU.CLASSIC)
  T.check_eq(T.game().lang, T.LANG.FR, "game in French again")
  T.press(T.K.A)
  T.check_eq(T.game().current, "A", "first key of the top row is A (AZERTY)")
  T.quit(true)
end)
