#!/usr/bin/env python3
"""Turn text word lists into the C tables embedded in the ROM.

usage: gen_wordlist.py <lang> <solutions.txt> <valid.txt> -o <outbase>

Emits <outbase>.c / <outbase>.h with, for LANG = <lang>:
    const char LANG_solutions[N][5]      solution words, in list order
    const char LANG_valid[M][5]          all accepted guesses, sorted (bsearch)
    const u16  LANG_challenge_seq[N]     fixed pseudo-random permutation of the
                                         solution indices used by Challenge mode
Words are stored upper-case, 5 bytes each, no terminator.
"""
import argparse
import random
import re
import sys

FIVE = re.compile(r"^[a-z]{5}$")


def load(path):
    words = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            w = line.strip().lower()
            if not w:
                continue
            if not FIVE.match(w):
                sys.exit(f"{path}: bad word {w!r}")
            words.append(w)
    return words


def c_words(words, per_line=10):
    out = []
    for i in range(0, len(words), per_line):
        out.append("    " + ",".join(f'"{w.upper()}"' for w in words[i:i + per_line]) + ",")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("lang")
    ap.add_argument("solutions")
    ap.add_argument("valid")
    ap.add_argument("-o", "--out", required=True)
    a = ap.parse_args()

    solutions = load(a.solutions)
    if len(set(solutions)) != len(solutions):
        sys.exit("duplicate solution words")
    valid = sorted(set(load(a.valid)) | set(solutions))

    # Deterministic shuffle: the Challenge sequence must be identical in every
    # build so that challenge #n is the same word for everyone.
    seq = list(range(len(solutions)))
    random.Random(f"wordle-gba-{a.lang}").shuffle(seq)

    L = a.lang
    with open(a.out + ".h", "w", newline="\n") as f:
        f.write(f"// Generated by gen_wordlist.py -- do not edit\n")
        f.write(f"#ifndef WORDLIST_{L.upper()}_H\n#define WORDLIST_{L.upper()}_H\n\n")
        f.write(f"#define {L.upper()}_SOLUTION_COUNT {len(solutions)}\n")
        f.write(f"#define {L.upper()}_VALID_COUNT {len(valid)}\n")
        f.write(f"extern const char {L}_solutions[{len(solutions)}][5];\n")
        f.write(f"extern const char {L}_valid[{len(valid)}][5];\n")
        f.write(f"extern const unsigned short {L}_challenge_seq[{len(solutions)}];\n")
        f.write("\n#endif\n")

    with open(a.out + ".c", "w", newline="\n") as f:
        f.write(f"// Generated by gen_wordlist.py -- do not edit\n")
        f.write(f"// {len(solutions)} solutions, {len(valid)} valid words\n\n")
        # 5-byte words carry no NUL terminator: tell GCC not to warn about it
        f.write("#if defined(__GNUC__) && __GNUC__ >= 8\n"
                "#define NONSTRING __attribute__((nonstring))\n"
                "#else\n#define NONSTRING\n#endif\n\n")
        f.write(f"const char {L}_solutions[{len(solutions)}][5] NONSTRING = {{\n{c_words(solutions)}\n}};\n\n")
        f.write(f"const char {L}_valid[{len(valid)}][5] NONSTRING = {{\n{c_words(valid)}\n}};\n\n")
        f.write(f"const unsigned short {L}_challenge_seq[{len(solutions)}] = {{\n")
        for i in range(0, len(seq), 16):
            f.write("    " + ",".join(str(x) for x in seq[i:i + 16]) + ",\n")
        f.write("};\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
