#!/usr/bin/env python3
"""PNG -> GBA 4bpp tile data + palette, exported as C arrays (grit replacement).

usage: png2gba.py image.png -o outbase [--meta W H] [--name NAME] [--no-pal]

* The image is cut into 8x8 tiles, in reading order. With --meta W H, tiles
  are emitted metatile by metatile (each W x H tiles, reading order inside),
  so a 16x16 object is 4 consecutive tiles.
* Indexed ("P" mode) images are used as-is: pixel value = palette index
  (must be < 16). Other images are quantised: colour 0 is transparent (the
  first pixel colour, or magenta #FF00FF if present), then colours in order
  of first appearance; more than 16 colours is an error.
* Output: outbase.c / outbase.h with
      const unsigned int   NAMETiles[]   4bpp tiles (32 bytes each)
      const unsigned short NAMEPal[16]   BGR555 palette
  and size #defines.
"""
import argparse
import os
import sys
from PIL import Image


def rgb15(r, g, b):
    return (r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10)


def load_indexed(path):
    """Return (width, height, pixel index getter, palette list of RGB)."""
    img = Image.open(path)
    if img.mode == "P":
        pal = img.getpalette()[: 16 * 3]
        palette = [tuple(pal[i:i + 3]) for i in range(0, len(pal), 3)]
        px = img.load()
        w, h = img.size
        for y in range(h):
            for x in range(w):
                if px[x, y] >= 16:
                    sys.exit(f"{path}: pixel ({x},{y}) uses index {px[x, y]} >= 16")
        return w, h, (lambda x, y: px[x, y]), palette

    img = img.convert("RGBA")
    w, h = img.size
    src = img.load()
    palette = []
    lut = {}
    first = src[0, 0][:3]
    transparent = (255, 0, 255) if any(src[x, y][:3] == (255, 0, 255)
                                       for y in range(h) for x in range(w)) else first
    palette.append(transparent)
    lut[transparent] = 0
    idx = [[0] * w for _ in range(h)]
    for y in range(h):
        for x in range(w):
            r, g, b, a = src[x, y]
            c = transparent if a < 128 else (r, g, b)
            if c not in lut:
                if len(palette) >= 16:
                    sys.exit(f"{path}: more than 16 colours")
                lut[c] = len(palette)
                palette.append(c)
            idx[y][x] = lut[c]
    return w, h, (lambda x, y: idx[y][x]), palette


def tile_words(get, tx, ty):
    """One 8x8 tile as 8 little-endian u32 rows (pixel 0 in low nibble)."""
    words = []
    for y in range(8):
        word = 0
        for x in range(8):
            word |= (get(tx * 8 + x, ty * 8 + y) & 0xF) << (4 * x)
        words.append(word)
    return words


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("image")
    ap.add_argument("-o", "--out", required=True, help="output base path (no extension)")
    ap.add_argument("--meta", nargs=2, type=int, metavar=("W", "H"), default=(1, 1),
                    help="metatile size in tiles")
    ap.add_argument("--name", help="C symbol prefix (default: derived from output name)")
    ap.add_argument("--no-pal", action="store_true", help="do not export the palette")
    a = ap.parse_args()

    w, h, get, palette = load_indexed(a.image)
    if w % 8 or h % 8:
        sys.exit(f"{a.image}: size {w}x{h} is not a multiple of 8")
    tw, th = w // 8, h // 8
    mw, mh = a.meta
    if tw % mw or th % mh:
        sys.exit(f"{a.image}: {tw}x{th} tiles not divisible by metatile {mw}x{mh}")

    name = a.name or os.path.basename(a.out).replace("gfx_", "")
    tiles = []
    for my in range(th // mh):
        for mx in range(tw // mw):
            for sy in range(mh):
                for sx in range(mw):
                    tiles.append(tile_words(get, mx * mw + sx, my * mh + sy))

    palette = (palette + [(0, 0, 0)] * 16)[:16]
    n_tiles = len(tiles)
    guard = f"GFX_{name.upper()}_H"
    with open(a.out + ".h", "w") as f:
        f.write(f"// Generated by png2gba.py from {os.path.basename(a.image)} -- do not edit\n")
        f.write(f"#ifndef {guard}\n#define {guard}\n\n")
        f.write(f"#define {name}TilesLen {n_tiles * 32}\n")
        f.write(f"#define {name}TileCount {n_tiles}\n")
        f.write(f"#define {name}MetaCount {n_tiles // (mw * mh)}\n")
        f.write(f"extern const unsigned int {name}Tiles[{n_tiles * 8}];\n")
        if not a.no_pal:
            f.write(f"#define {name}PalLen 32\n")
            f.write(f"extern const unsigned short {name}Pal[16];\n")
        f.write(f"\n#endif\n")

    with open(a.out + ".c", "w") as f:
        f.write(f"// Generated by png2gba.py from {os.path.basename(a.image)} -- do not edit\n")
        f.write(f"// {w}x{h} px, {n_tiles} tiles, metatile {mw}x{mh}\n\n")
        f.write(f"const unsigned int {name}Tiles[{n_tiles * 8}] __attribute__((aligned(4))) = {{\n")
        for t in tiles:
            f.write("    " + ",".join(f"0x{wd:08X}" for wd in t) + ",\n")
        f.write("};\n\n")
        if not a.no_pal:
            f.write(f"const unsigned short {name}Pal[16] __attribute__((aligned(4))) = {{\n    ")
            f.write(",".join(f"0x{rgb15(*c):04X}" for c in palette))
            f.write("\n};\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
