// Per-language data: word lists, keyboard layout, UI strings.
// Strings use the font's character set only: A-Z 0-9 ! ? : . - / % > < # ' ,
#include "lang.h"
#include "wordlist_en.h"
#include "wordlist_fr.h"

const Language languages[LANG_COUNT] = {
    [LANG_FR] = {
        .name          = "FRANCAIS",
        .solutions     = fr_solutions,
        .n_solutions   = FR_SOLUTION_COUNT,
        .valid         = fr_valid,
        .n_valid       = FR_VALID_COUNT,
        .kb_rows       = { "AZERTYUIOP", "QSDFGHJKLM", "\x01WXCVBN\x02" },

        .press_start        = "APPUYEZ SUR START",
        .menu_language      = "LANGUE",
        .menu_classic       = "CLASSIQUE",
        .menu_marathon      = "MARATHON",
        .difficulty         = { "FACILE", "DIFFICILE" },
        .menu_stats         = "STATISTIQUES",
        .menu_sound         = "SON",
        .on                 = "OUI",
        .off                = "NON",
        .menu_help          = "A: CHOISIR   </>: MODIFIER",
        .mode_classic       = "CLASSIQUE",
        .msg_too_short      = "MOT TROP COURT",
        .msg_not_in_list    = "MOT INCONNU",
        .win_msgs           = { "GENIAL !", "MAGNIFIQUE !", "IMPRESSIONNANT !",
                                "SPLENDIDE !", "SUPER !", "OUF !" },
        .lose_msg           = "PERDU ! C'ETAIT ",
        .stats_title        = "STATISTIQUES",
        .stats_played       = "PARTIES",
        .stats_win_rate     = "VICTOIRES",
        .stats_streak       = "SERIE",
        .stats_max_streak   = "RECORD",
        .stats_distribution = "REPARTITION DES ESSAIS",
        .stats_back         = "B: RETOUR",
        .result_prompt      = "A: REJOUER   B: MENU",
        .marathon_score     = "SCORE",
        .marathon_best      = "RECORD",
        .marathon_over      = "MARATHON TERMINE",
        .new_record         = "NOUVEAU RECORD !",
        .quit_confirm       = "QUITTER ?  A: OUI  B: NON",
        .game_help          = "A:LETTRE B:EFFACER START:OK",
    },
    [LANG_EN] = {
        .name          = "ENGLISH",
        .solutions     = en_solutions,
        .n_solutions   = EN_SOLUTION_COUNT,
        .valid         = en_valid,
        .n_valid       = EN_VALID_COUNT,
        .kb_rows       = { "QWERTYUIOP", "ASDFGHJKL", "\x01ZXCVBNM\x02" },

        .press_start        = "PRESS START",
        .menu_language      = "LANGUAGE",
        .menu_classic       = "CLASSIC",
        .menu_marathon      = "MARATHON",
        .difficulty         = { "EASY", "HARD" },
        .menu_stats         = "STATISTICS",
        .menu_sound         = "SOUND",
        .on                 = "ON",
        .off                = "OFF",
        .menu_help          = "A: SELECT   </>: CHANGE",
        .mode_classic       = "CLASSIC",
        .msg_too_short      = "NOT ENOUGH LETTERS",
        .msg_not_in_list    = "NOT IN WORD LIST",
        .win_msgs           = { "GENIUS!", "MAGNIFICENT!", "IMPRESSIVE!",
                                "SPLENDID!", "GREAT!", "PHEW!" },
        .lose_msg           = "THE WORD WAS ",
        .stats_title        = "STATISTICS",
        .stats_played       = "PLAYED",
        .stats_win_rate     = "WINS",
        .stats_streak       = "STREAK",
        .stats_max_streak   = "BEST",
        .stats_distribution = "GUESS DISTRIBUTION",
        .stats_back         = "B: BACK",
        .result_prompt      = "A: PLAY AGAIN   B: MENU",
        .marathon_score     = "SCORE",
        .marathon_best      = "BEST",
        .marathon_over      = "MARATHON OVER",
        .new_record         = "NEW RECORD!",
        .quit_confirm       = "QUIT?  A: YES  B: NO",
        .game_help          = "A:LETTER B:DELETE START:ENTER",
    },
};
