// Per-language data: word lists, keyboard layout, UI strings.
// Strings use the font's character set only: A-Z 0-9 ! ? : . - / % > < # ' ,
#include "lang.h"
#include "wordlist_en.h"
#include "wordlist_fr.h"

const Language languages[LANG_COUNT] = {
    [LANG_FR] = {
        .name        = "FRANCAIS",
        .solutions   = fr_solutions,
        .n_solutions = FR_SOLUTION_COUNT,
        .valid       = fr_valid,
        .n_valid     = FR_VALID_COUNT,
        .kb_rows     = { "AZERTYUIOP", "QSDFGHJKLM", "\x01WXCVBN\x02" },

        .press_start        = "APPUYEZ SUR START",
        .menu_classic       = "CLASSIQUE",
        .menu_marathon      = "MARATHON",
        .menu_time_attack   = "TIME ATTACK",
        .menu_records       = "RECORDS",
        .menu_stats         = "STATISTIQUES",
        .menu_options       = "OPTIONS",
        .menu_help          = "A: OK   B: RETOUR",
        .options_title      = "OPTIONS",
        .opt_language       = "LANGUE",
        .opt_sound          = "SON",
        .on                 = "OUI",
        .off                = "NON",
        .difficulty         = { "FACILE", "DIFFICILE" },
        .words              = "MOTS",
        .best               = "RECORD",
        .select_help        = "A: COMMENCER   B: RETOUR",
        .mode_classic       = "CLASSIQUE",
        .score              = "SCORE",
        .word               = "MOT",
        .msg_too_short      = "MOT TROP COURT",
        .msg_not_in_list    = "MOT INCONNU",
        .win_msgs           = { "GENIAL !", "MAGNIFIQUE !", "IMPRESSIONNANT !",
                                "SPLENDIDE !", "SUPER !", "OUF !" },
        .lose_msg           = "PERDU ! C'ETAIT ",
        .game_help          = "A:LETTRE B:EFFACER START:OK",
        .quit_confirm       = "QUITTER ?  A: OUI  B: NON",
        .result_prompt      = "A: REJOUER   B: MENU",
        .marathon_over      = "MARATHON TERMINE",
        .new_record         = "NOUVEAU RECORD !",
        .ta_done            = "TIME ATTACK TERMINE",
        .time               = "TEMPS",
        .penalties          = "PENALITES",
        .enter_initials     = "VOS INITIALES",
        .initials_help      = "HAUT/BAS: LETTRE   A: SUIVANT",
        .records_title      = "RECORDS",
        .records_help       = "</>: PAGE   B: RETOUR",
        .stats_title        = "STATISTIQUES",
        .stats_played       = "PARTIES",
        .stats_win_rate     = "VICTOIRES",
        .stats_streak       = "SERIE",
        .stats_max_streak   = "RECORD",
        .stats_distribution = "REPARTITION DES ESSAIS",
        .stats_back         = "B: RETOUR",
    },
    [LANG_EN] = {
        .name        = "ENGLISH",
        .solutions   = en_solutions,
        .n_solutions = EN_SOLUTION_COUNT,
        .valid       = en_valid,
        .n_valid     = EN_VALID_COUNT,
        .kb_rows     = { "QWERTYUIOP", "ASDFGHJKL", "\x01ZXCVBNM\x02" },

        .press_start        = "PRESS START",
        .menu_classic       = "CLASSIC",
        .menu_marathon      = "MARATHON",
        .menu_time_attack   = "TIME ATTACK",
        .menu_records       = "RECORDS",
        .menu_stats         = "STATISTICS",
        .menu_options       = "OPTIONS",
        .menu_help          = "A: OK   B: BACK",
        .options_title      = "OPTIONS",
        .opt_language       = "LANGUAGE",
        .opt_sound          = "SOUND",
        .on                 = "ON",
        .off                = "OFF",
        .difficulty         = { "EASY", "HARD" },
        .words              = "WORDS",
        .best               = "BEST",
        .select_help        = "A: START   B: BACK",
        .mode_classic       = "CLASSIC",
        .score              = "SCORE",
        .word               = "WORD",
        .msg_too_short      = "NOT ENOUGH LETTERS",
        .msg_not_in_list    = "NOT IN WORD LIST",
        .win_msgs           = { "GENIUS!", "MAGNIFICENT!", "IMPRESSIVE!",
                                "SPLENDID!", "GREAT!", "PHEW!" },
        .lose_msg           = "THE WORD WAS ",
        .game_help          = "A:LETTER B:DELETE START:ENTER",
        .quit_confirm       = "QUIT?  A: YES  B: NO",
        .result_prompt      = "A: PLAY AGAIN   B: MENU",
        .marathon_over      = "MARATHON OVER",
        .new_record         = "NEW RECORD!",
        .ta_done            = "TIME ATTACK COMPLETE",
        .time               = "TIME",
        .penalties          = "PENALTIES",
        .enter_initials     = "YOUR INITIALS",
        .initials_help      = "UP/DOWN: LETTER   A: NEXT",
        .records_title      = "RECORDS",
        .records_help       = "</>: PAGE   B: BACK",
        .stats_title        = "STATISTICS",
        .stats_played       = "PLAYED",
        .stats_win_rate     = "WINS",
        .stats_streak       = "STREAK",
        .stats_max_streak   = "BEST",
        .stats_distribution = "GUESS DISTRIBUTION",
        .stats_back         = "B: BACK",
    },
};
